---
- name: Pull docker image of Calculator
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull neelabhpb/spe-mini-project2023
      
    - name: running container
      shell: docker run -it -d neelabhpb/spe-mini-project2023
